#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Select a first-pass final training pack from the ranked open-access "
            "shortlist, targeting a fixed number of images per style."
        )
    )
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "reviews"
        / "open_access_shortlist_round1_master.csv",
        help="Ranked shortlist CSV generated by build_open_access_shortlist.py",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "reviews"
        / "open_access_final_train8_per_style.csv",
        help="Final selected training pack CSV.",
    )
    parser.add_argument(
        "--output-summary",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "reviews"
        / "open_access_final_train8_summary.json",
        help="Summary JSON for the selected training pack.",
    )
    parser.add_argument(
        "--picks-per-style",
        type=int,
        default=8,
        help="Target number of selected references per style.",
    )
    return parser.parse_args()


def to_int(value: str) -> int:
    try:
        return int(str(value).strip())
    except Exception:  # noqa: BLE001
        return 0


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def build_priority_buckets(style_rows: list[dict[str, str]]) -> list[tuple[str, list[dict[str, str]]]]:
    rows = sorted(
        style_rows,
        key=lambda row: (
            row.get("owner_match") != "yes",
            -to_int(row.get("shortlist_score", "0")),
            -to_int(row.get("original_score", "0")),
            row.get("title", "").lower(),
        ),
    )

    def matches(row: dict[str, str], *, owner: str | None = None, min_score: int | None = None) -> bool:
        if owner is not None and row.get("owner_match") != owner:
            return False
        if min_score is not None and to_int(row.get("shortlist_score", "0")) < min_score:
            return False
        return True

    buckets = [
        (
            "style_anchor",
            [row for row in rows if matches(row, owner="yes", min_score=55)],
        ),
        (
            "style_support",
            [
                row
                for row in rows
                if row.get("recommended_role") in {"core_train", "style_support"}
                and matches(row, owner="yes", min_score=35)
            ],
        ),
        (
            "cross_style_fallback",
            [
                row
                for row in rows
                if row.get("owner_match") == "no" and to_int(row.get("shortlist_score", "0")) >= 65
            ],
        ),
        (
            "deep_fallback",
            [row for row in rows if to_int(row.get("shortlist_score", "0")) >= 30],
        ),
        ("last_resort", rows),
    ]
    return buckets


def select_rows(rows: list[dict[str, str]], picks_per_style: int) -> list[dict[str, str]]:
    by_style: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        by_style[row["style"]].append(row)

    selected: list[dict[str, str]] = []
    for style in sorted(by_style):
        chosen: list[dict[str, str]] = []
        seen: set[tuple[str, str]] = set()
        for bucket_name, bucket_rows in build_priority_buckets(by_style[style]):
            for row in bucket_rows:
                key = (row.get("source_key", ""), row.get("external_id", ""))
                if key in seen:
                    continue
                seen.add(key)
                chosen_row = dict(row)
                chosen_row["selection_bucket"] = bucket_name
                chosen_row["train_pick"] = "yes"
                chosen_row["selection_note"] = selection_note(bucket_name, chosen_row)
                chosen.append(chosen_row)
                if len(chosen) >= picks_per_style:
                    break
            if len(chosen) >= picks_per_style:
                break

        for index, row in enumerate(chosen, start=1):
            row["train_style_rank"] = str(index)
        selected.extend(chosen)

    return selected


def selection_note(bucket_name: str, row: dict[str, str]) -> str:
    if bucket_name == "style_anchor":
        return "Strong owner-match reference for this style family."
    if bucket_name == "style_support":
        return "Owner-match support image with useful sketch/render cues."
    if bucket_name == "cross_style_fallback":
        return "High-score fallback from another style bucket; review before final training."
    if bucket_name == "deep_fallback":
        return "Fallback pick added to reach the target count; manual review recommended."
    return "Last-resort fallback; replace if a better official reference appears."


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0].keys())
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_summary(path: Path, rows: list[dict[str, str]], picks_per_style: int) -> None:
    by_style: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        by_style[row["style"]].append(row)

    payload = {
        "generated_by": "build_open_access_final_train_pack.py",
        "picks_per_style": picks_per_style,
        "selected_row_count": len(rows),
        "styles": {},
    }
    for style in sorted(by_style):
        style_rows = by_style[style]
        payload["styles"][style] = {
            "selected_count": len(style_rows),
            "owner_match_count": sum(1 for row in style_rows if row.get("owner_match") == "yes"),
            "fallback_count": sum(1 for row in style_rows if row.get("selection_bucket") in {"cross_style_fallback", "deep_fallback", "last_resort"}),
            "top_titles": [row.get("title", "") for row in style_rows[:3]],
        }

    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    rows = read_rows(args.input_csv.resolve())
    selected = select_rows(rows, args.picks_per_style)
    write_csv(args.output_csv.resolve(), selected)
    write_summary(args.output_summary.resolve(), selected, args.picks_per_style)
    print(f"Wrote {len(selected)} selected rows to {args.output_csv.resolve()}")
    print(f"Wrote summary to {args.output_summary.resolve()}")


if __name__ == "__main__":
    main()
